kind: pipeline
type: docker
name: testing

steps:
- name: migration db
  image: postgres
  depends_on:
    - db
  commands:
    - export PGPASSWORD=iniPassword
    - while ! pg_isready -U noobee -d detroit -h db ; do sleep 1; done
    - cat docs/schema.sql | psql -d detroit -U noobee -h db

- name: integration-tests
  image: golang
  environment:
    DB_HOST: db
    DB_PORT: 5432
    DB_USER: noobee
    DB_PASS: iniPassword
    DB_NAME: detroit
    DB_MAX_OPEN_CONN: 25
    DB_MAX_IDLE_CONN: 10
    DB_MAX_LIFETIME_CONN: 10
    DB_MAX_IDLETIME_CONN: 10
    GIN_MODE: release
  depends_on:
    - "migration db"
  commands:
    - sh test.sh

services:
- name: db
  image: postgres
  environment:
    POSTGRES_PASSWORD: iniPassword
    POSTGRES_USER: noobee
    POSTGRES_DB: detroit

---
kind: pipeline
type: docker
name: build-image

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    dockerfile: Dockerfile
    repo: achimonchi/detroit-testing
    tags: latest

depends_on:
- testing

---
kind: pipeline
type: docker
name: deploy-apps

clone:
  disable: true

steps:
- name: deploy to server
  image: appleboy/drone-ssh
  settings:
    host:
      - 103.76.120.94
    username: 
      from_secret: ssh_username
    password:
      from_secret: ssh_password
    port: 22
    command_timeout: 2m
    script:
      - cd apps
      - docker run -d --name detroit-test --env-file .env achimonchi/detroit-testing

depends_on:
- build-image


trigger:
  branch:
  - master
  - develop
  event:
  - push