kind: pipeline
type: docker
name: default

steps:
- name: migration db
  image: postgres
  environment:
    POSTGRES_PASSWORD: iniPassword
    POSTGRES_USER: noobee
    POSTGRES_DB: detroit
  depends_on:
    - db
  commands:
    - cat docs/schema.sql | psql -d detroit -U noobee -h db
- name: tests
  image: golang
  environment:
    DB_HOST: db
    DB_PORT: 5432
    DB_USER: noobee
    DB_PASS: iniPassword
    DB_NAME: detroit
    DB_MAX_OPEN_CONN: 25
    DB_MAX_IDLE_CONN: 10
    DB_MAX_LIFETIME_CONN: 10
    DB_MAX_IDLETIME_CONN: 10
    GIN_MODE: release
  depends_on:
    - db
  commands:
  - sh test.sh

services:
- name: db
  image: postgres
  environment:
    POSTGRES_PASSWORD: iniPassword
    POSTGRES_USER: noobee
    POSTGRES_DB: detroit

trigger:
  branch:
  - master
  - develop
  event:
  - push