kind: pipeline
type: docker
name: default

steps:
- name: tests
  image: golang
  depends_on:
    - db
  commands:
  - sh test.sh

services:
- name: db
  image: postgres
  environment:
    POSTGRES_PASSWORD: iniPassword
    POSTGRES_USER: noobee
    POSTGRES_DB: blog

trigger:
  branch:
  - develop
  event:
  - push