kind: pipeline
type: docker
name: default

steps:
- name: tests
  image: alpine
  depends_on:
    - db
  commands:
  - sh test.sh

services:
- name: db
  image: postgres
  environtment:
    POSTGRES_PASSWORD:iniPassword
    POSTGRES_USER:noobee
    POSTGRES_DB:blog

trigger:
  branch:
  - develop
  - master
  event:
  - push