kind: pipeline
type: docker
name: default

steps:
- name: tests
  image: golang
  commands:
  - ping db
  - sh test.sh

services:
- name: db
  image: postgres
  environtment:
    POSTGRES_PASSWORD:iniPassword
    POSTGRES_USER:noobee
    POSTGRES_DB:blog