kind: pipeline
type: docker
name: default

steps:
- name: golang
  image: alpine
  commands:
  - sh test.sh

services:
- name: db
  image: postgres
  environtment:
    POSTGRES_PASSWORD:iniPassword
    POSTGRES_USER:noobee
    POSTGRES_DB:blog